### ISSUE TITLE
Add one additional link to Originating portal

### ISSUE THREAD

**Issue by MichaelOstling** [GeoCat/iso-19139-to-dcat-ap#2]
For each originating portal we have separate syntax for how to access each record.
We need to check with Jose if we still have this function at Geodataportalen 

At eg our PlanningCatalogue we use the following call
https://ext-geodatakatalog-forv.lansstyrelsen.se/PlaneringsKatalogen/?querystring=uuid=(7a7c75ab-c51a-4565-864c-58d846165081_C)&site=DefaultUser

**Comment by pvgenuchten** [comment]
For stockholm i found this url
https://dataportalen.stockholm.se/dataportalen/GetMetaDataById?id=

naturvardsverket has
https://miljodataportalen.naturvardsverket.se/miljodataportalen/GetMetaDataURL?url=http://mdp01.vic-metria.nu:8082/geonetwork/srv/en/csw?request=GetRecordById!!!service=CSW!!!version=2.0.2!!!elementSetName=full!!!outputSchema=csw:IsoRecord!!!id=

geoportal.se has
https://www.geodata.se/geodataportalen/srv/api/records/

**Comment by pvgenuchten** [comment]
@josegar74 any guidance on this? do you know if alternative md-uri's available for these portals?
@MichaelOstling do you want me to add above url's for the time being?
