### ISSUE TITLE
WMS-URLs must get other Media-type

### ISSUE THREAD

**Issue by MetaGIS** [GeoCat/iso-19139-to-dcat-ap#3]
In portal we can't see any links to WMS-services
Check the format here
![image](https://user-images.githubusercontent.com/71434590/114265741-d20af180-99f2-11eb-85ed-79d6600a4325.png)

**Comment by pvgenuchten** [comment]
i'm replacing image/png for vnd.ogc.wfs_xml
i'm replacing application/gml+xml for vnd.ogc.wfs_xml

**Comment by pvgenuchten** [comment]
this is solved in https://github.com/GeoCat/iso-19139-to-dcat-ap/commit/434b83255416de3a6a634422da94b4f60c94ef3d, please confirm
